# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sdm_class_prj',
                'doc_host': 'https://Hemanth-Thaluru.github.io',
                'git_url': 'https://github.com/Hemanth-Thaluru/sdm_class_prj',
                'lib_path': 'sdm_class_prj'},
  'syms': { 'sdm_class_prj.core': {'sdm_class_prj.core.foo': ('core.html#foo', 'sdm_class_prj/core.py')},
            'sdm_class_prj.manual': {'sdm_class_prj.manual.foo': ('core.html#foo', 'sdm_class_prj/manual.py')}}}
